services:
  backend:
    build:
      context: ./backend
    container_name: habit-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATA_FILE=/app/data/habits.json
      - APP_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
    volumes:
      - habit_data:/app/data

volumes:
  habit_data:
